# Base name of the Google Sheet to use
# The code assumes that there is one sheet per year, with a space and YYYY after the name given here,
# e.g. "My Accounting 2022", "My Accounting 2023", etc. It will open the sheet
# corresponding to the current year.
sheet = "My Accounting"

[worksheets]
payment = "All payments"
coin = "Coin Daily Close"

[apikeys]
tiingo = "aVerySecretKey"

# Used by get-chainlink-activity to get payment
# Address of the wallet, contract address of the LINK token, column the payment should be recorded in on the payment sheet.
# The "provider","baseurl" and "apikey" are for the chain explorer. Possible values for provider "etherscan", "etherscan-all-cf" (required if behind
# CloudFlare, e.g. Optimism and Fantom explorers), "solana"
[wallets]
  [wallets.ethereum]
    "address" = "0xmyETHaddress"
    "contract" = "0x514910771af9ca656af840dff83e8264ecf986ca"
    "column" = "2"
    "provider" = "etherscan"
    "baseurl" = "https://api.etherscan.io"
    "apikey"= "my-etherscan-apikey"

# Used by get-chainlink-activity
# Nodes for which to get balance information. Type of the RPC node to query, possible values are "evm", "sol" or "terra",
# Worksheet Title for the node, URL of the RPC node to query, address of the account in the node.
# The "provider","baseurl" and "apikey" would be for detecting funding, currently unused. Possible values for provider "etherscan", "etherscan-all-cf" (required if behind
# CloudFlare, e.g. Optimism and Fantom explorers), "solana", "nada"
[nodes]
  [nodes.main_ocr]
    "type" = "evm"
    "worksheet-title" = "Mainnet OCR"
    "url" = "https://<my-rpc-node>"
    "address" = "0xmy-node-address"
    "provider" = "etherscan"
    "baseurl" = "https://api.etherscan.io"
    "apikey" = "my-etherscan-apikey"

# Used by get-closing-prices
# Any coins to query, with their ticker as recognized by the API, column in the "coin" worksheet, and API provider to use
# Tiingo does not cause 429s and is faster than coingecko
[coins]
  [coins.eth]
    "ticker" = "ethusd"
    "column" = "2"
    "provider" = "tiingo"
  [coins.matic]
    "ticker" = "maticusd"
    "column" = "3"
    "provider" = "tiingo"
  [coins.ftm]
    "ticker" = "ftmusd"
    "column" = "4"
    "provider" = "tiingo"
  [coins.ht]
    "ticker" = "htusd"
    "column" = "5"
    "provider" = "tiingo"
  [coins.link]
    "ticker" = "linkusd"
    "column" = "6"
    "provider" = "tiingo"
  [coins.movr]
    "ticker" = "movrusd"
    "column" = "7"
    "provider" = "tiingo"
  [coins.sol]
    "ticker" = "solusd"
    "column" = "8"
    "provider" = "tiingo"
  [coins.rpl]
    "ticker" = "rocket-pool"
    "column" = "9"
    "provider" = "coingecko"
  [coins.usdc]
    "ticker" = "usdcusd"
    "column" = "10"
    "provider" = "tiingo"
  [coins.luna]
    "ticker" = "lunausd"
    "column" = "11"
    "provider" = "tiingo"
